# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sql', models.TextField()),
                ('form_data', models.TextField(default=b'{}')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('num_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('form_data', models.TextField(blank=True, null=True)),
                ('parent_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BatchJob')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('data', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.JobTask')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('period_unit', models.CharField(choices=[(b'minutes', b'minutes'), (b'hours', b'hours'), (b'days', b'days')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_started_on', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BatchJob')),
            ],
        ),
        migrations.CreateModel(
            name='TaskBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobtask',
            name='parent_recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RecurringTask'),
        ),
    ]
