# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_batchjob_only_email_if_rows_above'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='database',
            field=models.CharField(default=b'ak', max_length=255),
        ),
    ]
