# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_batchjob_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTaskConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('recurring_tasks', models.ManyToManyField(to='main.RecurringTask')),
            ],
        ),
    ]
