# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recurringtaskconflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='run_via',
            field=models.CharField(choices=[(b'client-db', b'client-db'), (b'api', b'api')], default=b'client-db', max_length=20),
        ),
    ]
