# Generated by Django 3.1.5 on 2021-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191012_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='expected_num_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='run_via',
            field=models.CharField(choices=[('client-db', 'client-db'), ('api', 'api')], default='client-db', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='type',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
