# Generated by Django 3.1.5 on 2021-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210117_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
